//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyAttendence_tbl
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<System.TimeSpan> TimeIn { get; set; }
        public string TimeInImage { get; set; }
        public Nullable<System.TimeSpan> TimeOut { get; set; }
        public string TimeOutImage { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public string Accuracy { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
