//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTrack_tbl
    {
        public int Id { get; set; }
        public string UserID { get; set; }
        public string Lat { get; set; }
        public string Long { get; set; }
        public Nullable<System.TimeSpan> LatLongTime { get; set; }
        public string CurrentTimeInMilies { get; set; }
        public string CheckInImage { get; set; }
        public string CheckOutImage { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
