//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceMgmt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AttendenceMgmtEntities : DbContext
    {
        public AttendenceMgmtEntities()
            : base("name=AttendenceMgmtEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompanyRegistration_tbl> CompanyRegistration_tbl { get; set; }
        public virtual DbSet<DailyAttendence_tbl> DailyAttendence_tbl { get; set; }
        public virtual DbSet<Department_Master_tbl> Department_Master_tbl { get; set; }
        public virtual DbSet<Designation_Master_tbl> Designation_Master_tbl { get; set; }
        public virtual DbSet<EmployeeDetails_tbl> EmployeeDetails_tbl { get; set; }
        public virtual DbSet<EmployeeTrack_tbl> EmployeeTrack_tbl { get; set; }
        public virtual DbSet<Shift_Master_tbl> Shift_Master_tbl { get; set; }
        public virtual DbSet<SignIn_tbl> SignIn_tbl { get; set; }
    }
}
