//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendenceMgmt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignIn_tbl
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Usertype { get; set; }
        public string Department { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
